name: Deploy Backend to EC2 using Docker Compose

on:
  push:
    branches:
      - backend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Install SSH Client
      run: sudo apt-get install openssh-client

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh  # Ensure the .ssh directory exists
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa


    - name: SSH into EC2 and deploy
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_IP_ADDRESS }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          echo "Cloning or pulling the latest code from GitHub repository..."
          if [ -d "elib" ]; then
            cd elib && git pull origin backend
          else
            git clone https://github.com/skr2270/elib.git
          fi

          # Navigate to the backend directory where docker-compose.yml is located
          cd elib/backend

          # Check if Docker Compose is installed, if not, install it
          if ! command -v docker-compose &> /dev/null
          then
            echo "Docker Compose not found. Installing it..."
            sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
          fi

          echo "Building Docker images using Docker Compose..."
          docker-compose build  # Rebuild the image with the latest code

          echo "Restarting containers using Docker Compose..."
          docker-compose up -d  # Run the containers in detached mode
